#!/bin/bash 2> /dev/null
modprobe ahci > /dev/null 2> /dev/null
modprobe binfmt_misc > /dev/null 2> /dev/null
modprobe bridge > /dev/null 2> /dev/null
modprobe cdc_ether > /dev/null 2> /dev/null
modprobe cdrom > /dev/null 2> /dev/null
modprobe cnic > /dev/null 2> /dev/null
modprobe crc32c_intel > /dev/null 2> /dev/null
modprobe crc32_pclmul > /dev/null 2> /dev/null
modprobe crct10dif_pclmul > /dev/null 2> /dev/null
modprobe cxgb4 > /dev/null 2> /dev/null
modprobe cxgb4i > /dev/null 2> /dev/null
modprobe dm_crypt > /dev/null 2> /dev/null
modprobe dm_log > /dev/null 2> /dev/null
modprobe dm_mirror > /dev/null 2> /dev/null
modprobe dm_mod > /dev/null 2> /dev/null
modprobe dm_multipath > /dev/null 2> /dev/null
modprobe dm_region_hash > /dev/null 2> /dev/null
modprobe drm > /dev/null 2> /dev/null
modprobe drm_kms_helper > /dev/null 2> /dev/null
modprobe e1000e > /dev/null 2> /dev/null
modprobe ext4 > /dev/null 2> /dev/null
modprobe fat > /dev/null 2> /dev/null
modprobe fb_sys_fops > /dev/null 2> /dev/null
modprobe fuse > /dev/null 2> /dev/null
modprobe ghash_clmulni_intel > /dev/null 2> /dev/null
modprobe hid_multitouch > /dev/null 2> /dev/null
modprobe i2c_algo_bit > /dev/null 2> /dev/null
modprobe i2c_designware_core > /dev/null 2> /dev/null
modprobe i2c_designware_platform > /dev/null 2> /dev/null
modprobe i2c_hid > /dev/null 2> /dev/null
modprobe i2c_i801 > /dev/null 2> /dev/null
modprobe i915 > /dev/null 2> /dev/null
modprobe ib_cm > /dev/null 2> /dev/null
modprobe ib_core > /dev/null 2> /dev/null
modprobe ib_ipoib > /dev/null 2> /dev/null
modprobe ib_iser > /dev/null 2> /dev/null
modprobe ib_isert > /dev/null 2> /dev/null
modprobe ib_srp > /dev/null 2> /dev/null
modprobe ib_srpt > /dev/null 2> /dev/null
modprobe ib_umad > /dev/null 2> /dev/null
modprobe ib_uverbs > /dev/null 2> /dev/null
modprobe idma64 > /dev/null 2> /dev/null
modprobe int3400_thermal > /dev/null 2> /dev/null
modprobe int3403_thermal > /dev/null 2> /dev/null
modprobe int340x_thermal_zone > /dev/null 2> /dev/null
modprobe intel_cstate > /dev/null 2> /dev/null
modprobe intel_gtt > /dev/null 2> /dev/null
modprobe intel_hid > /dev/null 2> /dev/null
modprobe intel_pch_thermal > /dev/null 2> /dev/null
modprobe intel_pmc_core > /dev/null 2> /dev/null
modprobe intel_powerclamp > /dev/null 2> /dev/null
modprobe intel_rapl > /dev/null 2> /dev/null
modprobe intel_rapl_perf > /dev/null 2> /dev/null
modprobe intel_soc_dts_iosf > /dev/null 2> /dev/null
modprobe intel_uncore > /dev/null 2> /dev/null
modprobe intel_wmi_thunderbolt > /dev/null 2> /dev/null
modprobe ip6_tables > /dev/null 2> /dev/null
modprobe ip_set > /dev/null 2> /dev/null
modprobe ip_tables > /dev/null 2> /dev/null
modprobe ipt_MASQUERADE > /dev/null 2> /dev/null
modprobe ipt_REJECT > /dev/null 2> /dev/null
modprobe irqbypass > /dev/null 2> /dev/null
modprobe iscsi_boot_sysfs > /dev/null 2> /dev/null
modprobe iscsi_target_mod > /dev/null 2> /dev/null
modprobe iscsi_tcp > /dev/null 2> /dev/null
modprobe isofs > /dev/null 2> /dev/null
modprobe iTCO_vendor_support > /dev/null 2> /dev/null
modprobe iTCO_wdt > /dev/null 2> /dev/null
modprobe iw_cm > /dev/null 2> /dev/null
modprobe iw_cxgb4 > /dev/null 2> /dev/null
modprobe jbd2 > /dev/null 2> /dev/null
modprobe joydev > /dev/null 2> /dev/null
modprobe kvm > /dev/null 2> /dev/null
modprobe kvm_intel > /dev/null 2> /dev/null
modprobe ledtrig_audio > /dev/null 2> /dev/null
modprobe libahci > /dev/null 2> /dev/null
modprobe libata > /dev/null 2> /dev/null
modprobe libcrc32c > /dev/null 2> /dev/null
modprobe libcxgb > /dev/null 2> /dev/null
modprobe libcxgbi > /dev/null 2> /dev/null
modprobe libiscsi > /dev/null 2> /dev/null
modprobe libiscsi_tcp > /dev/null 2> /dev/null
modprobe llc > /dev/null 2> /dev/null
modprobe loop > /dev/null 2> /dev/null
modprobe mbcache > /dev/null 2> /dev/null
modprobe mei > /dev/null 2> /dev/null
modprobe mei_me > /dev/null 2> /dev/null
modprobe mei_wdt > /dev/null 2> /dev/null
modprobe memstick > /dev/null 2> /dev/null
modprobe mii > /dev/null 2> /dev/null
modprobe mmc_core > /dev/null 2> /dev/null
modprobe nf_conntrack > /dev/null 2> /dev/null
modprobe nf_conntrack_ipv4 > /dev/null 2> /dev/null
modprobe nf_conntrack_ipv6 > /dev/null 2> /dev/null
modprobe nf_conntrack_tftp > /dev/null 2> /dev/null
modprobe nf_defrag_ipv4 > /dev/null 2> /dev/null
modprobe nf_defrag_ipv6 > /dev/null 2> /dev/null
modprobe nf_nat > /dev/null 2> /dev/null
modprobe nf_nat_ipv4 > /dev/null 2> /dev/null
modprobe nf_nat_ipv6 > /dev/null 2> /dev/null
modprobe nf_nat_tftp > /dev/null 2> /dev/null
modprobe nfnetlink > /dev/null 2> /dev/null
modprobe nf_reject_ipv4 > /dev/null 2> /dev/null
modprobe nf_reject_ipv6 > /dev/null 2> /dev/null
modprobe nf_tables > /dev/null 2> /dev/null
modprobe nf_tables_set > /dev/null 2> /dev/null
modprobe nft_chain_nat_ipv4 > /dev/null 2> /dev/null
modprobe nft_chain_nat_ipv6 > /dev/null 2> /dev/null
modprobe nft_chain_route_ipv4 > /dev/null 2> /dev/null
modprobe nft_chain_route_ipv6 > /dev/null 2> /dev/null
modprobe nft_compat > /dev/null 2> /dev/null
modprobe nft_counter > /dev/null 2> /dev/null
modprobe nft_ct > /dev/null 2> /dev/null
modprobe nft_fib > /dev/null 2> /dev/null
modprobe nft_fib_inet > /dev/null 2> /dev/null
modprobe nft_fib_ipv4 > /dev/null 2> /dev/null
modprobe nft_fib_ipv6 > /dev/null 2> /dev/null
modprobe nft_objref > /dev/null 2> /dev/null
modprobe nft_reject > /dev/null 2> /dev/null
modprobe nft_reject_inet > /dev/null 2> /dev/null
modprobe nls_utf8 > /dev/null 2> /dev/null
modprobe nvme > /dev/null 2> /dev/null
modprobe nvme_core > /dev/null 2> /dev/null
modprobe overlay > /dev/null 2> /dev/null
modprobe pcspkr > /dev/null 2> /dev/null
modprobe pinctrl_cannonlake > /dev/null 2> /dev/null
modprobe pinctrl_intel > /dev/null 2> /dev/null
modprobe processor_thermal_device > /dev/null 2> /dev/null
modprobe qla4xxx > /dev/null 2> /dev/null
modprobe r8152 > /dev/null 2> /dev/null
modprobe rdma_cm > /dev/null 2> /dev/null
modprobe rdma_ucm > /dev/null 2> /dev/null
modprobe rfkill > /dev/null 2> /dev/null
modprobe rpcrdma > /dev/null 2> /dev/null
modprobe rtsx_pci > /dev/null 2> /dev/null
modprobe rtsx_pci_ms > /dev/null 2> /dev/null
modprobe rtsx_pci_sdmmc > /dev/null 2> /dev/null
modprobe scsi_transport_iscsi > /dev/null 2> /dev/null
modprobe scsi_transport_srp > /dev/null 2> /dev/null
modprobe sd_mod > /dev/null 2> /dev/null
modprobe serio_raw > /dev/null 2> /dev/null
modprobe sg > /dev/null 2> /dev/null
modprobe snd > /dev/null 2> /dev/null
modprobe snd_compress > /dev/null 2> /dev/null
modprobe snd_hda_codec > /dev/null 2> /dev/null
modprobe snd_hda_codec_generic > /dev/null 2> /dev/null
modprobe snd_hda_codec_hdmi > /dev/null 2> /dev/null
modprobe snd_hda_codec_realtek > /dev/null 2> /dev/null
modprobe snd_hda_core > /dev/null 2> /dev/null
modprobe snd_hda_ext_core > /dev/null 2> /dev/null
modprobe snd_hda_intel > /dev/null 2> /dev/null
modprobe snd_hwdep > /dev/null 2> /dev/null
modprobe snd_pcm > /dev/null 2> /dev/null
modprobe snd_rawmidi > /dev/null 2> /dev/null
modprobe snd_seq > /dev/null 2> /dev/null
modprobe snd_seq_device > /dev/null 2> /dev/null
modprobe snd_soc_acpi > /dev/null 2> /dev/null
modprobe snd_soc_acpi_intel_match > /dev/null 2> /dev/null
modprobe snd_soc_core > /dev/null 2> /dev/null
modprobe snd_soc_hdac_hda > /dev/null 2> /dev/null
modprobe snd_soc_skl > /dev/null 2> /dev/null
modprobe snd_soc_skl_ipc > /dev/null 2> /dev/null
modprobe snd_soc_sst_dsp > /dev/null 2> /dev/null
modprobe snd_soc_sst_ipc > /dev/null 2> /dev/null
modprobe snd_sof > /dev/null 2> /dev/null
modprobe snd_sof_intel_byt > /dev/null 2> /dev/null
modprobe snd_sof_intel_hda > /dev/null 2> /dev/null
modprobe snd_sof_intel_hda_common > /dev/null 2> /dev/null
modprobe snd_sof_intel_ipc > /dev/null 2> /dev/null
modprobe snd_sof_xtensa_dsp > /dev/null 2> /dev/null
modprobe snd_timer > /dev/null 2> /dev/null
modprobe snd_usb_audio > /dev/null 2> /dev/null
modprobe snd_usbmidi_lib > /dev/null 2> /dev/null
modprobe sof_pci_dev > /dev/null 2> /dev/null
modprobe soundcore > /dev/null 2> /dev/null
modprobe sparse_keymap > /dev/null 2> /dev/null
modprobe squashfs > /dev/null 2> /dev/null
modprobe sr_mod > /dev/null 2> /dev/null
modprobe stp > /dev/null 2> /dev/null
modprobe sunrpc > /dev/null 2> /dev/null
modprobe syscopyarea > /dev/null 2> /dev/null
modprobe sysfillrect > /dev/null 2> /dev/null
modprobe sysimgblt > /dev/null 2> /dev/null
modprobe tap > /dev/null 2> /dev/null
modprobe target_core_mod > /dev/null 2> /dev/null
modprobe tun > /dev/null 2> /dev/null
modprobe uas > /dev/null 2> /dev/null
modprobe uio > /dev/null 2> /dev/null
modprobe usbnet > /dev/null 2> /dev/null
modprobe usb_storage > /dev/null 2> /dev/null
modprobe vfat > /dev/null 2> /dev/null
modprobe vhost > /dev/null 2> /dev/null
modprobe vhost_net > /dev/null 2> /dev/null
modprobe video > /dev/null 2> /dev/null
modprobe wmi > /dev/null 2> /dev/null
modprobe wmi_bmof > /dev/null 2> /dev/null
modprobe x86_pkg_temp_thermal > /dev/null 2> /dev/null
modprobe xt_CHECKSUM > /dev/null 2> /dev/null
modprobe xt_conntrack > /dev/null 2> /dev/null
